### ISSUE TITLE
dataset 

### ISSUE THREAD

**Issue by susht3** [danoyu/AS_project-Skim-RNN#2]
can you provide the dataset? or where to download the dataset?

**Comment by danoyu** [comment]
The dataset is rotten tomatoes you can find it on kaggle

**Comment by susht3** [comment]
i download the dataset，and then run train.py， but i get this error:

Traceback (most recent call last):
  File "train.py", line 34, in <module>
    lang.load("preprocessing_RT")
  File "/data1/susht3/workspace/AS_project-Skim-RNN/preprocesser.py", line 77, in load
    self.corpus = pkl.load(open(filename+"_corpus.pkl", 'rb'))
FileNotFoundError: [Errno 2] No such file or directory: 'preprocessing_RT_corpus.pkl'

where is 'preprocessing_RT_corpus.pkl' ?
